core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

easyparty/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from easyparty import settings
admin.site.site_header = 'DjangoEasyParty'

urlpatterns = [
    path('', include('core.urls')),
    path('', include('invitation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

invitation/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('invites/', views.invites_list, name='invites_list'),
    path('invite/create/', views.invite_create, name='invite_create'),
    path('invite/share/<pk>/', views.invite_share, name="invite_share"),
    path('invite/update/<pk>/', views.invite_update, name='invite_update'),
    path('invite/public/<pk>/<slug>/', views.invite_public, name="invite_public"),
    path('invite/download/<pk>/<slug>/', views.invite_download_jpg, name='invite_download_jpg')
]

invitation/models.py
import uuid

from django.db import models

from core.models import Active, TimeStampedModel


class InviteCategory(models.Model):
    name = models.CharField('Nome', max_length=50)
    description = models.TextField('Descrição')

    def __str__(self):
        return str(self.pk) + ' - ' + str(self.name)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'


class InviteTemplate(Active, TimeStampedModel):
    name = models.CharField('Nome', max_length=50)
    description = models.TextField('Descrição', blank=True, null=True)
    categories = models.ManyToManyField(InviteCategory)
    background_image = models.ImageField('Background', blank=True)
    title_font = models.FileField('Fonte do título', blank=True)
    body_font = models.FileField('Fonte do corpo', blank=True)
    title_text = models.CharField('Título', default='Título', max_length=100)
    body_text = models.TextField('Corpo do texto', default='Corpo do texto')
    title_size = models.PositiveIntegerField('Tamanho do título', default=170)
    body_size = models.PositiveIntegerField('Tamanho do texto', default=70)
    title_pos = models.PositiveIntegerField('Posição do título', default=600)
    body_pos = models.PositiveIntegerField('Posição do texto', default=800)
    invite_data = models.TextField('invite_data', blank=True, null=True)

    def __str__(self):
        return str(self.pk) + ' - ' + str(self.name)

    class Meta:
        verbose_name = 'modelo'
        verbose_name_plural = 'modelos'


def make_slug():
    return str(uuid.uuid4())


class Invite(Active, TimeStampedModel):
    # GENDER_CHOICES = (
    #     (0, 'Chá Revelação'),
    #     (1, 'Menino'),
    #     (2, 'Menina'),
    # )
    name = models.CharField('Nome', max_length=20)
    age = models.PositiveIntegerField('Idade')
    # gender = models.IntegerField('Genero', choices=GENDER_CHOICES)
    date = models.DateField('Data')
    start_time = models.TimeField('Hora de início')
    end_time = models.TimeField('Hora de termino')
    maximum_guests = models.PositiveIntegerField('Máximo de Convidados')
    invite_template = models.ForeignKey(InviteTemplate,
                                        on_delete=models.CASCADE, blank=True,
                                        null=True)
    slug = models.CharField(max_length=36, default=make_slug())

    class Meta:
        ordering = ('date', 'start_time', 'name',)
        verbose_name_plural = "convites"
        verbose_name = "convite"


class GuestInvite(models.Model):
    invite = models.ForeignKey(Invite, on_delete=models.CASCADE)
    name = models.CharField('Nome do Convidado', max_length=20)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "convidados"
        verbose_name = "convidado"

invitation/forms.py
from django.forms import ModelForm, TextInput, Select, DateInput, TimeInput
from django.utils.translation import gettext_lazy as _

from .models import Invite


class InviteForm(ModelForm):
    class Meta:
        model = Invite
        fields = [
            'name',
            'age',
            'invite_template',
            'date',
            'start_time',
            'end_time',
            'maximum_guests',
        ]
        labels = {
            'name': _('Nome'),
            'age': _('Idade'),
            'invite_template': _('Modelo'),
            'date': _('Data'),
            'start_time': _('Hora início'),
            'end_time': _('Hora fim'),
        }
        help_texts = {
            'name': _('Digite o nome que deve aparecer no convite'),
            'age': _('Digite a idade do aniversariante, ou 0 (zero) para chá de revelação'),
        }

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'age': TextInput(attrs={'class': 'form-control'}),
            'invite_template': Select(attrs={'class': 'form-control'}),
            'date': DateInput(attrs={'class': 'form-control'}),
            'start_time': TimeInput(attrs={'class': 'form-control'}),
            'end_time': TimeInput(attrs={'class': 'form-control'}),
            'maximum_guests': TextInput(attrs={'class': 'form-control'}),
        }

invitation/views.py
from io import BytesIO

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .facade import make_invite
from .forms import InviteForm
from .models import Invite


@login_required
def invite_create(request):
    if request.method == 'POST':
        form = InviteForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                messages.success(request, "Convite cadastrado.")
                return redirect('invites_list')
        except Exception as e:
            messages.warning(request, f'Ocorreu um erro ao atualizar: {e}')

    else:
        form = InviteForm()

    return render(request, 'invitation/create.html', {'form': form})


@login_required
def invite_update(request, pk):
    invite = get_object_or_404(Invite, pk=pk)

    if request.method == 'POST':
        form = InviteForm(request.POST, instance=invite)
        try:
            if form.is_valid():
                form.save()
                messages.success(request, "Convite atualizado.")
                return redirect('invite_update', pk)
        except Exception as e:
            messages.warning(request, f'Ocorreu um erro ao atualizar: {e}')

    else:
        form = InviteForm(instance=invite)

    return render(request, 'invitation/update.html', {'form': form})


@login_required
def invites_list(request):
    all_invites = Invite.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(all_invites, 10)
    try:
        invites = paginator.page(page)
    except PageNotAnInteger:
        invites = paginator.page(1)
    except EmptyPage:
        invites = paginator.page(paginator.num_pages)
    return render(request, 'invitation/invites.html', context={'invites': invites})


def invite_download_jpg(request, pk, slug):
    content = make_invite(pk=pk, slug=slug)
    byte = BytesIO()

    content.image.save(byte, 'JPEG')
    byte.seek(0)

    response = FileResponse(byte, 'rb')
    response['Content-Disposition'] = f'attachment; filename={content.file_name}-{content.date}.jpg'
    return response


@login_required
def invite_share(request, pk):
    invite = get_object_or_404(Invite, pk=pk)
    url = request.build_absolute_uri(reverse('invite_public', kwargs={'pk': invite.pk, 'slug': invite.slug}))

    return render(request, 'invitation/share.html', {'invite': invite,
                                                     'url': url})


def invite_public(request, pk, slug):
    invite = get_object_or_404(Invite, pk=pk, slug=slug)

    return render(request, 'invitation/public.html', {'invite': invite})

templates/invitation/create.html
{% extends "base.html" %}
{% block title %}Convites{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>Novo convite</h2>
        </div>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="col-12">
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message|safe }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% if form.errors %}
                <div class="col-12">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ form.errors }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            {% endif %}
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_name">Nome</label>
                    {{ form.name }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_age">Idade</label>
                    {{ form.age }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_gender">Tipo</label>
                    {{ form.invite_template }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="id_date">Data</label>
                    {{ form.date }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_start_time">Início</label>
                    {{ form.start_time }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_end_time">Termino</label>
                    {{ form.end_time }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_maximum_guests">Convidados</label>
                    {{ form.maximum_guests }}
                </div>
            </div>
            <button class="btn btn-success mt-2 mb-4"><i class="far fa-save"></i> Salvar</button>
        </form>

    </div>
{% endblock content %}
{% block extra_js %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/4.0.9/jquery.inputmask.bundle.min.js" integrity="sha256-O4r2M4p1dxfVFgKvwK23D1RQdTU8ABlIBir9aGP+KJY=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $("#id_date").inputmask("99/99/9999", {"placeholder": "DD/MM/AAAA"});
            $("#id_start_time").inputmask("99:99", {"placeholder": "HH:MM"});
            $("#id_end_time").inputmask("99:99", {"placeholder": "HH:MM"});
        });
    </script>

{% endblock %}

templates/invitation/invites.html
{% extends "base.html" %}
{% block title %}Convites{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col md-6">
                <h2>Convites</h2>
            </div>
            <div class="col md-6">
                <a href="{% url 'invite_create' %}" class="btn btn-success float-right"><i class="fas fa-plus-circle"></i> Novo</a>
            </div>
        </div>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="col-12">
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message|safe }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table">
                    <caption>Convites</caption>
                    <thead>
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col" style="text-align: center;">Festa</th>
                        <th scope="col" style="text-align: center;">Data</th>
                        <th scope="col" style="text-align: center;">Hora</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for invite in invites %}
                        <tr>
                            <th class="align-middle" style="white-space: nowrap;" scope="row">{{ invite.name }}</th>
                            <td class="align-middle" style="text-align: center;">
                                <span class="badge badge-pill" style="background-color: #17a2b8;">{{ invite.invite_template }}</span>
                            </td>
                            <td class="align-middle" style="white-space: nowrap; text-align: center;">{{ invite.date }}</td>
                            <td class="align-middle" style="text-align: center;">{{ invite.start_time }}</td>
                            <td class="align-middle" style="white-space: nowrap; text-align: right;">
                                <a href="{% url 'invite_update' pk=invite.pk %}" class="btn btn-sm btn-outline-info" role="button" aria-pressed="true" data-toggle="tooltip" data-placement="top" title="Editar">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="{% url 'invite_share' pk=invite.pk %}" class="btn btn-sm btn-outline-info" role="button" aria-pressed="true" data-toggle="tooltip" data-placement="top" title="Compartilhar">
                                    <i class="fas fa-share"></i>
                                </a>
                                <a href="{% url 'invite_public' pk=invite.pk slug=invite.slug %}" class="btn btn-sm btn-outline-info" role="button" aria-pressed="true" data-toggle="tooltip" data-placement="top" title="Link">
                                    <i class="fas fa-link"></i>
                                </a>
                                <a href="{% url 'invite_download_jpg' pk=invite.pk slug=invite.slug %}" class="btn btn-sm btn-outline-info" role="button" aria-pressed="true" data-toggle="tooltip" data-placement="top" title="Download">
                                    <i class="fas fa-file-download"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {#                {% if invites.has_other_pages %}#}
                <nav aria-label="Search results pages">
                    <ul class="pagination">
                        {% if invites.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ invites.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in invites.paginator.page_range %}
                            {% if invites.number == i %}
                                <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if invites.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ invites.next_page_number }}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                </nav>
                {#                {% endif %}#}

            </div>
        </div>
    </div>
{% endblock content %}
{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

templates/invitation/public.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Olá, você foi convidado para minha festa</title>
    <meta property="og:title" content="Olá, quero te convidar para minha festa"/>
    <meta property="og:description" content="data {{ invite.date }} a partir das {{ invite.start_time }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="Espaço Boo!">
    <meta property="og:url" content="{{ url }}"/>
    <meta property="og:image" content="{% static "favicon.png" %}"/>

    <!-- ==== Favicon ==== -->
    <link rel="icon" href="{% static "favicon.png" %}" type="image/png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>

    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
        }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
        }

        .container {
            padding: 2px 16px;
        }

        .card-img-caption {
            border-top-left-radius: calc(.25rem - 1px);
            border-top-right-radius: calc(.25rem - 1px);
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col d-flex justify-content-center">
            <div class="card" style="max-width: 480px">
                <div class="card-img-caption">
                    <img class="card-img-top" src="{% url 'invite_download_jpg' pk=invite.pk slug=invite.slug %}" alt="Background image" style="width:100%">
                </div>
                <div class="container d-flex justify-content-around">
                    <a target="_blank" class="btn btn-success my-4" href="https://goo.gl/maps/ShXSMDdU6rttJniX6" role="button"><i class="fas fa-map-marker"></i>
                        Como chegar
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/invitation/share.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Olá, você foi convidado para minha festa</title>
    <meta property="og:title" content="Olá, você foi convidado para minha festa - saiba mais: {{ url }}"/>
    <meta property="og:description" content="Descrição - saiba mais: {{ url }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="Espaço Boo!">
    <meta property="og:url" content="{{ url }}"/>
    <meta property="og:image" content="{% static "favicon.png" %}"/>

    <!-- ==== Favicon ==== -->
    <link rel="icon" href="{% static "favicon.png" %}" type="image/png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>

    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            transition: 0.3s;
        }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
        }

        .container {
            padding: 2px 16px;
        }

        .card-img-caption {
            border-top-left-radius: calc(.25rem - 1px);
            border-top-right-radius: calc(.25rem - 1px);
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col d-flex justify-content-center">
            <div class="card" style="max-width: 480px">
                <div class="card-img-caption">
                    <img class="card-img-top" src="{% url 'invite_download_jpg' pk=invite.pk slug=invite.slug %}" alt="Background image" style="width:100%">
                </div>
                <div class="container d-flex justify-content-between">
                    <a class="btn btn-primary my-4" href="{{ request.META.HTTP_REFERER }}" role="button"><i class="fas fa-chevron-circle-left"></i>
                        Voltar
                    </a>
                    <a class="btn btn-success my-4" href="https://api.whatsapp.com/send?text=Gostaria muito da sua presença, aqui está seu convite {{ url }}" role="button"><i class="fab fa-whatsapp"></i>
                        Compartilhar
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/invitation/update.html
{% extends "base.html" %}
{% block title %}Convites{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>Novo convite</h2>
        </div>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="col-12">
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message|safe }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% if form.errors %}
                <div class="col-12">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ form.errors }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            {% endif %}
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_name">Nome</label>
                    {{ form.name }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_age">Idade</label>
                    {{ form.age }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_gender">Tipo</label>
                    {{ form.invite_template }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="id_date">Data</label>
                    {{ form.date }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_start_time">Início</label>
                    {{ form.start_time }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_end_time">Termino</label>
                    {{ form.end_time }}
                </div>
                <div class="form-group col-md-3">
                    <label for="id_maximum_guests">Convidados</label>
                    {{ form.maximum_guests }}
                </div>
            </div>
            <div class="form-row d-flex justify-content-between">
                    <a class="btn btn-primary mt-2 mb-4" href="{{ request.META.HTTP_REFERER }}" role="button"><i class="fas fa-chevron-circle-left"></i>
                        Voltar
                    </a>
                    <button class="btn btn-success mt-2 mb-4"><i class="far fa-save"></i> Salvar</button>
            </div>
        </form>

    </div>
{% endblock content %}
{% block extra_js %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/4.0.9/jquery.inputmask.bundle.min.js" integrity="sha256-O4r2M4p1dxfVFgKvwK23D1RQdTU8ABlIBir9aGP+KJY=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $("#id_date").inputmask("99/99/9999", {"placeholder": "DD/MM/AAAA"});
            $("#id_start_time").inputmask("99:99", {"placeholder": "HH:MM"});
            $("#id_end_time").inputmask("99:99", {"placeholder": "HH:MM"});
        });
    </script>

{% endblock %}